### ISSUE TITLE
Missing deck-clearing & mind-blowing fireworks or something on Monday morning

### ISSUE THREAD

**Issue by ykarikos** [staltz/annankatu#10]
![screen shot 2015-03-23 at 08 00 11](https://cloud.githubusercontent.com/assets/845477/6765232/bf61bebc-cfdf-11e4-83c5-c3676436d4bc.png)

Any ideas?

**Comment by ykarikos** [comment]
http://js-fireworks.appspot.com/ ?

**Comment by staltz** [comment]
Pekka Pulli had the idea of putting some gif. I think we should definitely have something.

**Comment by staltz** [comment]
Done. Surprise will be published monday morning. :)
