### ISSUE TITLE
Oleg is biking the wrong route

### ISSUE THREAD

**Issue by jevakallio** [staltz/annankatu#6]
The video shows Oleg going by the Hietaniemi cemetery, but the route on the map goes down Porkkalankatu and through the center.

How do I submit a pull request that will make @phadej reshoot the video? :trollface:

**Comment by phadej** [comment]
@jevakallio you cannot, Helsinki used its sunny days quota :trollface:

**Comment by staltz** [comment]
I agree with @jevakallio. But before @phadej 's PR we need an automated test case for this.

**Comment by jsunfutu** [comment]
Can't you change the route on the map to go through the cemetery?

**Comment by jevakallio** [comment]
@jsunfutu no

**Comment by jevakallio** [comment]
@staltz how about we scatter broken glass and install trip wires on all the routes we don't want him to take, effectively guaranteeing that if the packet reaches target it will have had to move through the correct switches?

**Comment by miro** [comment]
Trying to reproduce and fix this on my local environment, what is the exact model of the bicycle?

**Comment by staltz** [comment]
Yes, but let's make that a separate library so we don't clutter this. I suggest `bikehint` would be the name.

**Comment by staltz** [comment]
@phadej what's your bicycle's exact model?

**Comment by phadej** [comment]
@miro @staltz  Pelago San Sebastian, but there is a problem:
- I have done few local patches
- which are applied on two year old upstream version
- Luckily, I'm pretty sure you can apply patches to the newest version too; did some refactoring recently.

**Comment by staltz** [comment]
Nothing that docker won't solve. You have it in docker, right?

**Comment by phadej** [comment]
I think there might be some problems with DRM :S bycycles are tricky

**Comment by kpuputti** [comment]
![Posting in epic thread](https://img.4plebs.org/boards/s4s/image/1409/43/1409431420270.png)

**Comment by daniellandau** [comment]
Tangentially relevant: http://en.wikipedia.org/wiki/IP_over_Avian_Carriers
